### ISSUE TITLE
`DownloadFileAsync` 和 `DownloadQueueAsync` 均为同步函数

### ISSUE THREAD

**Issue by Timothy-Liuxf** [eesast/THUAI7#231]
installer 中 `DownloadFileAsync` 和 `DownloadQueueAsync` 均被声明为 `async` 函数，但这个 `async` 是毫无意义的，此函数的实现依然是同步的实现。

C# 中，`async` 和 `await` 两个关键字需成对出现——包含 `await` 的函数一定是 `async` 函数，而被声明为 `async` 的函数内部如果没有 `await` 则是无意义的。因为异步函数执行到 `await` 语句中的异步函数并且递归地如此操作，直到执行到最深层的 `await` 处的 `Task.Run`，才会在线程池 `System.Threading.Threadpool` 中开一个新的线程，并将控制权返回给调用者（C# 的 `async` 本质上是 `Task` 的语法糖）；如果没有 `await` 语句，改“异步”函数将直接顺序执行到末尾，与同步函数无任何差别。

建议 `DownloadFileAsync` 和 `DownloadQueueAsync` 直接改为等价的同步函数以节约性能和避免误解：

```diff
- public async Task<int> DownloadFileAsync(string savePath, string? remotePath = null);
+ public int DownloadFile(string savePath, string? remotePath = null);

- public async Task<int> DownloadQueueAsync(string basePath, IEnumerable<string> queue);
+ public int DownloadQueue(string basePath, IEnumerable<string> queue);
```

同理，`WaitAll` 等等实际上都是不必要的：

```csharp
Task.WaitAll(tocpp, topy, tncpp, tnpy);
```

---

关于并行下载：

并行下载的并行能力由 `Parallel.ForEach` 提供，和异步函数没有关系，所以把异步函数改回同步函数不会对并行下载能力有影响。

---

一点其他的想法（待讨论）

`DownloadQueueAsync` 的 `async` 也许并不是没有意义，例如使用 `await Parallel.ForEachAsync` 等，使得并行下载是异步的，也许可以直接作为 UI 下载的回调函数内调用的函数，以防止阻塞 UI 线程等。这样 `Update` 函数和 `Install` 函数也要被声明为 `async`，而 `DownloadBtnClicked` 内就不用写“`Task.Run`”了：

https://github.com/eesast/THUAI7/blob/6262aa1c00e489b2fdfedbfed98a8c44bbfc1736/installer/ViewModel/InstallViewModel.cs#L184-L191

=>

```csharp
 if (Downloader.Data.Installed) 
 { 
     await Downloader.ResetInstallPath(DownloadPath); 
 } 
 else 
 { 
     await Downloader.Install(DownloadPath); 
 } 
```
因为 `Task.Run` 在 `Parallel.ForEachAsync` 内启动了。

**Comment by DreamEnderKing** [comment]
目前实现方法是将上述同步实现的“异步”方法声明为同步方法，然后新建异步方法，在异步方法中用`Task.Run()`调用原方法，这样可以有效规避c#递归查询最底层异步方法，导致“异步”方法实际上同步运行。同时所有与UI相关的事件采用`Timer`采样，防止因异步导致触发UI更新事件过多过密，产生的UI闪烁/卡顿等问题。
