### ISSUE TITLE
船只被摧毁后不能重建

### ISSUE THREAD

**Issue by DragonAura** [eesast/THUAI7#296]
**Describe the bug**
船只被摧毁后不能重建

**To Reproduce**
- 设置基地代码为重复刷新某种船
- 用敌方船只对己方舰船进行攻击
- 己方船只被摧毁
- 再次等到经济足够

**Expected behavior**
船只被正常建造，并扣除对应的经济

**Screenshots**
![image](https://github.com/eesast/THUAI7/assets/32223554/083e16bb-79e2-42c3-9397-8b46cdf21f18)

**Additional context**
显然蓝队建造了两次军用舰船（观察经济），然而并没有对应的军用舰船被造出来，并且后续建造也全部失败，不确定是Server端的问题还是logic内部的问题

**Comment by shangfengh** [comment]
应当为logic的问题

**Comment by DragonAura** [comment]
造出来的船血量为 0
