### ISSUE TITLE
不能启动多个MAUI Debug界面

### ISSUE THREAD

**Issue by DragonAura** [eesast/THUAI7#297]
**Describe the bug**
不能启动多个MAUI Debug界面

**To Reproduce**
- 按照下面 Screenshots 里的设置启动 Client

**Expected behavior**
游戏正常启动，出现两个 MAUI Debug Client

**Screenshots**
![image](https://github.com/eesast/THUAI7/assets/32223554/54687134-696a-4f90-b899-d3e15cfb6fb7)

![image](https://github.com/eesast/THUAI7/assets/32223554/a1efff3f-6bac-4b7c-a40e-baec401c1341)

**Additional context**
从上图可以看出，虽然 Debug 界面启动了两个，但是两个的 PlayerID 与 TeamID 都是相同的，推测是因为在启动器启动时过快地连续启动了两个 Client，同时没有对应地正确更改启动的 json 配置

**Comment by DreamEnderKing** [comment]
已经解决。
