### ISSUE TITLE
经济自然增长错误

### ISSUE THREAD

**Issue by DragonAura** [eesast/THUAI7#344]
**Describe the bug**
经济自然增长错误

**To Reproduce**
- CAPI空代码直接运行
- 经济有时可以正常增长，有时都不增长，有时只有一队增长

**Expected behavior**
两队都正常经济增长

**Comment by asdawej** [comment]
**复现:**
- 启动器Python 设置舰船脚本为 `api.Attack(0)`，队伍脚本为 `api.BuildShip(MilitaryShip)`
- Visual Studio本地服务器设置 `WarShipCost = 1`、`ShipCount = 2`
- 为了便于调试，设置 `WarShipSpeed = 5000`
- 启动器启动 0 队 Player2 为 Manual

**Screenshot:**
![image](https://github.com/eesast/THUAI7/assets/52828818/2504cb86-3c3d-4626-a36b-5156b55b70db)

可以发现，0队经济锁定于为4999. 图示情况为操控 0队 Player2 撞上 1队 Player2 的攻击后重新建造，因此 0队经济变为 4998.

随后 0队 Player2 消灭 1队 Player2，由于 `WarShipCost = 1`，0队经济不增加.

**Comment by asdawej** [comment]
**Screenshot:**

![image](https://github.com/eesast/THUAI7/assets/52828818/9a1b5e8a-8b4d-43aa-bb75-76286d28fda7)
