### ISSUE TITLE
观战者屏蔽MessageOfNews

### ISSUE THREAD

**Issue by DragonAura** [eesast/THUAI7#363]
**Is your feature request related to a problem? Please describe.**
WebGL 方面，接收二进制消息后会乱码出 BUG

**Describe the solution you'd like**
Server 端直接屏蔽掉消息

**Describe alternatives you've considered**
解码端自己屏蔽消息

**Comment by DragonAura** [comment]
https://stackoverflow.com/questions/45978846/determine-which-oneof-proto3-field-is-set-in-c-sharp

写成类似于下面这种形式：

```csharp
if (msg != null && msg.MessageOfObjCase != MessageOfObj.MessageOfObjOneofCase.NewsMessage) currentGameInfo.ObjMessage.Add(msg);
```

即可 @GuoWQ222

**Comment by GuoWQ222** [comment]
已在server端删除NewsMessage

**Comment by GuoWQ222** [comment]
通过创建currentGameInfo的深拷贝删除NewsMessage
