### ISSUE TITLE
Separate the color part of the texture to produce more color varients

### ISSUE THREAD

**Issue by asdawej** [eesast/THUAI7#73]
> > Can the color part of the texture be separated in order to produce more color varients?
> 
> The color part of the textures may be too complex to be seperated. It should get the balance between the texture seperation along with more complex system and the drawing work.

Simply adding a mask will work, I suppose. It is not that complex.

_Originally posted by @Panxuc in https://github.com/eesast/THUAI7/issues/72#issuecomment-1878615393_

**Comment by hhzzff** [comment]
事实上可以做到程序化更改颜色，只需要将特征颜色的部分扣除更改遮罩颜色即可，不过我认为这方面并没有特别的需求。

**Comment by hhzzff** [comment]
该特性已引入，现在特殊单位可以在代码中自定义颜色。
